### ISSUE TITLE
Code completion in JS buffer?

### ISSUE THREAD

**Issue by sandric** [NicolasPetton/Indium#125]
I added `(add-hook 'js-mode-hook #'indium-interaction-mode)` to indium interaction mode to work in existing files js buffers, but it looks like company completion works only in either repl or scratch. Is it on purpose? Is there a way to enable the same completion in existing js buffers?

**Comment by NicolasPetton** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by NicolasPetton** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @NicolasPetton.

**Comment by NicolasPetton** [comment]
I could enable the same completion in all JavaScript buffers, but you wouldn't get context-aware completion: the completion in indium is the same as the completion in Chrome's console, it's asking the runtime to complete as you type, and it won't perform any type inference on your project or anything like that.

If what you want is proper completion with type inference, I suggest using ternjs, it's doing a pretty good job!

**Comment by kandros** [comment]
I suggest using [tide](https://github.com/ananthakumaran/tide) instead, it uses the same language server used by visual studio code and allow for context-aware, file/module-aware code completion and refactoring

**Comment by sandric** [comment]
Ok thanks, I tried to use tide in past, but with little luck, tried again recently and looks like it works pretty fine, although I struggle sometimes to find recent list of libs and modules list. I think issue should be closed then, @NicolasPetton should I?

**Comment by NicolasPetton** [comment]
Yes, I'm closing the issue.
