### ISSUE TITLE
Having issue with the debugger

### ISSUE THREAD

**Issue by bobrowadam** [NicolasPetton/Indium#137]
I'm having issues getting the debugger to work, not sure if I'm doing something wrong.
Im using `indium-run-node` to start my node app and it seems to work fine yet the app doesn't stop on break points unless I'm using the `--debug-brk` option. This also works only until a certain point in which the debugger stops, again, before it reaches my break point.
Any suggestions?

**Comment by NicolasPetton** [comment]
Breakpoints will be added to the JS runtime after the evaluation of your `node` program. This is because node has to be running for the breakpoints to be added.

It means that if you run `node` with a file that exits after the evaluation (unlike starting an HTTP server for example), breakpoints might be added too late.

Let me give you an example, let's say you have a `foo.js` file with 

```js
function add(a, b) {
  return a + b;
}

add(3,4);
```

If you start indium with `M-x indium-run-node RET node ./foo.js RET`, then node starts, evaluates `foo.js`, then your breakpoints are added (after the invocation of node, so the file has already been evaluated).

The `--debug-brk` option (or better, setting `indium-nodejs-inspect-brk` to `t`) will make `node` pause on the first statement, giving time for Indium to add the breakpoints.

**Comment by NicolasPetton** [comment]
The latest commit in master sets `indium-nodejs-inspect-brk` to `t` by default, which is probably less confusing.

**Comment by bobrowadam** [comment]
Ok I understand, Thanks for the quick reply :)

**Comment by NicolasPetton** [comment]
Cool, closing the issue then!
