### ISSUE TITLE
Question: Babel support

### ISSUE THREAD

**Issue by tamoore** [NicolasPetton/Indium#142]
I've yet to actually try Indium but it looks great, so thank you for the project. 👏 

I noticed Webpack support but I couldn't find any documentation about whether Indium supports projects that just use babel?

Normally, as a repl, I would use `babel-node` (Babel CLI).

**Comment by NicolasPetton** [comment]
Todd Moore <notifications@github.com> writes:

> I noticed Webpack support but I couldn't find any documentation about
> whether Indium supports projects that just use babel.

There should be nothing special for babel, as long as the sourcemap
files work as expected.

> Normally, as a repl, I would use `babel-node` (Babel CLI).

That might be another thing, could you give it a try? I'm not using
babel-node myself.

**Comment by NicolasPetton** [comment]
@tamoore do you know more about this issue? I'd like to know if everything works fine for you.

**Comment by NicolasPetton** [comment]
@baerrach I don't understand how this is related to Indium, can you elaborate a bit more?

**Comment by baerrach** [comment]
It's in response to @tamoore's original question, can you use the babel-node as a REPL.

The answer is yes - sortof.

Once you have babel-node configured correctly (I didn't when I posted my previous comment) you can get Indium to use babel-node. However babel-node generates temporary files which it deletes and so Emacs opens an empty buffer to a file that does not exist. You can still invoke the REPL commands but there is no context to know what is going on. I could not find anyway to get babel-node to write the transpiled files somewhere.

To work around this problem you can invoke babel by hand `babel src --out-dir lib --source-maps-inline` and then just use normal node to run the files. At this point you have to wonder why am I bothering? The file will have all of the transpiled guff in it and is an output of the babel process. So when you want to make changes you need to go back to the input file, make your edit, re-run babel, re-run Indium.

And since you are no longer running babel-node but plain node instead why not go the extra step and make your code Node compliant instead?

Additionally, even when running under babel-node, you can not use any non-Node code as module and require are passed into the module when it gets invoked and unless you close over them they will no longer be in scope continue hacking on with.
