### ISSUE TITLE
The REPL starts but immediately get  ECONNREFUSED

### ISSUE THREAD

**Issue by ignaciocaamanio** [NicolasPetton/Indium#196]
I'm using Indium 20181206.1044, Node 11.4.0 (nvm), Archlinux. 
After executing `M-: indium-connect` the REPL launches but I get: `Indium server error: connect ECONNREFUSED 127.0.0.1:9229`

I've tried with different ports and nothing.

.indium.json is:
`{
    "configurations": [
        {
            "name": "Web project",
            "type": "node",
            "port": 9229
        }
    ]
}`

**Comment by ignaciocaamanio** [comment]
I didn't, how do i start the node process?

**Comment by NicolasPetton** [comment]
You can add a command to be executed in your configuration like the following:

```
{
  "configurations": [
    {
      "name": "Web project",
      "type": "node",
      "command": "node ./index.js",
      "port": 9229
    }
  ]
}
```

And start indium with `M-x indium-launch`, which will start the process for you.
See https://indium.readthedocs.io/en/latest/setup.html#nodejs-configuration-options

Otherwise, you can start the node process yourself, adding the `--inspect` flag, and connect to it with `M-x indium-connect`.

**Comment by ignaciocaamanio** [comment]
Thank you, I think the problem was that I didn't have this line: `"command": "node ./index.js",`

But now I have another problem...
`Indium server error: Cannot find context with specified id` 

Thank you for your help!

**Comment by NicolasPetton** [comment]
Great! I'm closing this one then. 

Could you open another ticket detailing the issue you're facing now? Thanks!

**Comment by ignaciocaamanio** [comment]
Ok!!
