### ISSUE TITLE
Indium server error

### ISSUE THREAD

**Issue by ignaciocaamanio** [NicolasPetton/Indium#198]
After M-x: indium-launch the REPL starts but when I try to evaluate something I get: 
`Indium server error: Cannot find context with specified id`

**Comment by NicolasPetton** [comment]
Hi,

Could you tell me more about your setup?  Do you connect to a node process or chrome? 
It's also good to have a look at this page: https://indium.readthedocs.io/en/latest/troubleshooting.html

**Comment by ignaciocaamanio** [comment]
I connect to a node process, use nvm, emacs 26.1 on Linux.

**Comment by NicolasPetton** [comment]
Thank you.
I have a few other questions:
- What version of nodejs are you using?
- Are you sure you have a running process when you connect with Indium? If your node application is not a server, it might very well exit immediately, and Indium would try to connect too late. In that case, try adding `"inspect-brk": true` in your configuration as documented here: 
https://indium.readthedocs.io/en/latest/setup.html

**Comment by ignaciocaamanio** [comment]
I'm using node 11.6.0. I added `"inspect-brk": true` but when I go back to the REPL get the same "indium server error" when I want to evaluate something. Maybe I don't understand how it works Indium, I used it some long ago and I managed to make it work as a REPL to evaluate the code that I was writing. When I have time I'll give it a second look to understand it.

**Comment by jinlin82** [comment]
I have exact the same problem.
My config : Windows 7 64 bit + Emacs 26.1 + node-v10.15.1-win-x64

.indium.json file as following:

```
{
  "configurations": [
    {
      "name": "Web project",
      "type": "node",
      "command": "node ./abc.js",
      "port": 9229
    }
  ]
}
```

and I also try node.js 8.9 version and add  `"inspect-brk": true` but no luck.

**Comment by NicolasPetton** [comment]
@ignaciocaamanio is your project exiting after evaluating `node ./albums.js`?

If it the case then what happens is that Indium gets disconnected right after the evaluation of the file, because the node process exited, so you cannot evaluate anything anymore.

You can still debug it using `inspect-brk` as you mentioned, and use the REPL **while** you are debugging.  Node used to keep the process running for as long as the debugger was attached in Linux (but not in Windows AFAIR), but IIRC it is not the case anymore.

**Comment by aang7** [comment]
Same problem here, there is no way to achieve the evaluation of code without running the debugger yet?

**Comment by KhalfaniWadlington** [comment]
The config:
```
{
  "configurations": [
    {
      "name": "Web project",
      "type": "node",
      "command": "node ./abc.js",
      "port": 9229
    }
  ]
}
```
will not work because it is `command` is an invalid argument.

 The current docs say the command should be split between "program" and "args". Running this gave me `Indium server error: Cannot find context with specified id` because there was no context because the script had been run without pausing on a breakpoint or `debugger;` statement.

```
{
  "configurations": [
    {
      "name": "Web project",
      "type": "node",
      "program": "node ",
      "args": " ./abc.js",
      "port": 9229
    }
  ]
}
```


I used this config with  `"inspect-brk": true` and then ran `M-x: indium-launch`. This launched me into a debugger. I was able switch to the `*JS REPL*`buffer after the debugger paused on the first line
```
{
  "configurations": [
    {
      "name": "Debug abc.js",
      "type": "node",
      "program": "node ",
      "args": " ./abc.js",
      "inspect-brk": true,
      "port": 9229
    }
  ]
}
```
